package com.aop.schema;

import java.text.ParseException;
import java.util.Random;
import org.apache.commons.codec.binary.Base64;

public class Test {
	
	public static void main( String[] args ) throws ParseException{

System.out.println(randomNumberGenerator(1001,9999));	 

	byte[] dec = Base64.decodeBase64("iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAIAAAD6wG44AAAAA3NCSVQICAjb4U/gAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAVRSURBVHhe7d3BjRxlFEbR3mAPso1NDKSAWYIYJwEmAAdgbNKAAHA2OC400hGl4mnkO4tBA7yj2rWu9Etf96qrVJd3t7i6I1kmy2SZLJNlskyWyTLZsAMjy2SZLJNlsmEHRpbJMlkmy2TDDowsk2WyTJbJhh0YWSbLZJkskw07MLJMlskyWSYbdmBkmSyTZbJMNuzAyDJZJstkmWy4fHWL13cky2SZLJNlskyWyTJZJhsuvgCDL0Amy2SZLJNlskyWyTJZJht2YGSZLJNlskw27MDIMlkmy2SZbNiBkWWyTJbJMtmwAyPLZJksk2WyYQdGlskyWSbLZMMOjCyTZbJMlsmGHRhZJstkmSyTDTswskyWyTJZJht2YGSZLJNlskw27MDIMlkmy2SZbNiBkWWyTJbJMtmwAyPLZJksk2WyYQdGlskyWSbLZMMOjCyTZbJMlsmGy7e3+O6OZJksk2WyTJbJMlkmy2TD3tGBLJNlskyWyYYdGFkmy2SZLJMNOzCyTJbJMlkmG3ZgZJksk2WyTDbswMgyWSbLZJls2IGRZbJMlsky2bADI8tkmSyTZbJhB0aWyTJZJstkww6MLJNlskyWyYYdGFkmy2SZLJMNOzCyTJbJMlkmG3ZgZJksk2WyTDbswMgyWSbLZJls2IGRZbJMlsky2bADI8tkmSyTZbLh4vHSweOlmSyTZbJMlskyWSbLZJlsuDy+hS9AJstkmSyTZbJMlskyWSYb9pYdZJksk2WyTDbswMgyWSbLZJls2IGRZbJMlsky2bADI8tkmSyTZbJhB0aWyTJZJstkww6MLJNlskyWyYaHM/Db9z+/+/37648vnv+z17OPz7/88OrasTKnzmSZLJMNO/AO3Mgy2WEHPpFlsmEH3oEbWSY77MAnskw27MA7cCPLZIcd+ESWyYYdeAduZJns8PaXd+8/XL8aA9z39eyPL178lwf2+eDzTJbJDo+uHj1+8+TpGOC+r5tf8JunTxwrc+pMlsky2fCABv788dUO/BdZJht24B24kWWyww58Istkww68AzeyTHbYgU9kmWzYgXfgRpbJDjvwiSyTDTvwDtzIMtlhBz6RZbJhB96BG1kmO+zAJ7JMNuzAO3Ajy2SHHfhElsmGHfj/OrCnDzNZJjt89u/6u9CpM1kmy2TDw3lB9A8//fj6169fjgHu+7r5w/+3b146VubUmSyTZbJhb9m5+QXvLTufJstkhx34RJbJhh14B25kmeywA5/IMtmwA+/AjSyTHXbgE1kmG3bgHbiRZbLDDnwiy2TDDrwDN7JMdtiBT2SZbNiBd+BGlskOO/CJLJMNO/AO3Mgy2WEHPpFlsuHhDPwJskyWyTJZJstkmWy4eL/w4P3CmSyTZbJMlskyWSbLZJlseDi37HyCLJNlskyWyTJZJht2YGSZLJNlskw27MDIMlkmy2SZbNiBkWWyTJbJMtmwAyPLZJksk2WyYQdGlskyWSbLZMMOjCyTZbJMlsmGHRhZJstkmSyTDTswskyWyTJZJht2YGSZLJNlskw27MDIMlkmy2SZbNiBkWWyTJbJMtmwAyPLZJksk2WyYQdGlskyWSbLZMMOjCyTZbJMlsmGfUE0skyWyTJZJhv2jg5kmSyTZbJMNuzAyDJZJstkmWzYgZFlskyWyTLZsAMjy2SZLJNlsmEHRpbJMlkmy2TDDowsk2WyTJbJhh0YWSbLZJkskw07MLJMlskyWSYbdmBkmSyTZbJMNuzAyDJZJstkmWzYgZFlskyWyTLZsAMjy2SZLJNlsmEHRpbJMlkmy2TDDowsk2WyTJbJ/ubq6k8WX8yNDYiQUwAAAABJRU5ErkJggg==".getBytes());
	
	System.out.println(new String(dec));
	}
	
	public static String randomNumberGenerator(int startingValue,int endValue){
        Random random = new Random();
        Integer randomNumber = random.nextInt(endValue - startingValue) + startingValue;

        return randomNumber.toString();
    }
}
